imagick_file.lo: /home/jeaven5/public_html/solutions/ePOS/printer/imagick-3.4.4/imagick_file.c
	$(LIBTOOL) --mode=compile $(CC) -fopenmp -I/usr/include/ImageMagick   -I. -I/home/jeaven5/public_html/solutions/ePOS/printer/imagick-3.4.4 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/jeaven5/public_html/solutions/ePOS/printer/imagick-3.4.4/imagick_file.c -o imagick_file.lo 
imagick_class.lo: /home/jeaven5/public_html/solutions/ePOS/printer/imagick-3.4.4/imagick_class.c
	$(LIBTOOL) --mode=compile $(CC) -fopenmp -I/usr/include/ImageMagick   -I. -I/home/jeaven5/public_html/solutions/ePOS/printer/imagick-3.4.4 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/jeaven5/public_html/solutions/ePOS/printer/imagick-3.4.4/imagick_class.c -o imagick_class.lo 
imagickdraw_class.lo: /home/jeaven5/public_html/solutions/ePOS/printer/imagick-3.4.4/imagickdraw_class.c
	$(LIBTOOL) --mode=compile $(CC) -fopenmp -I/usr/include/ImageMagick   -I. -I/home/jeaven5/public_html/solutions/ePOS/printer/imagick-3.4.4 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/jeaven5/public_html/solutions/ePOS/printer/imagick-3.4.4/imagickdraw_class.c -o imagickdraw_class.lo 
imagickpixel_class.lo: /home/jeaven5/public_html/solutions/ePOS/printer/imagick-3.4.4/imagickpixel_class.c
	$(LIBTOOL) --mode=compile $(CC) -fopenmp -I/usr/include/ImageMagick   -I. -I/home/jeaven5/public_html/solutions/ePOS/printer/imagick-3.4.4 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/jeaven5/public_html/solutions/ePOS/printer/imagick-3.4.4/imagickpixel_class.c -o imagickpixel_class.lo 
imagickpixeliterator_class.lo: /home/jeaven5/public_html/solutions/ePOS/printer/imagick-3.4.4/imagickpixeliterator_class.c
	$(LIBTOOL) --mode=compile $(CC) -fopenmp -I/usr/include/ImageMagick   -I. -I/home/jeaven5/public_html/solutions/ePOS/printer/imagick-3.4.4 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/jeaven5/public_html/solutions/ePOS/printer/imagick-3.4.4/imagickpixeliterator_class.c -o imagickpixeliterator_class.lo 
imagick_helpers.lo: /home/jeaven5/public_html/solutions/ePOS/printer/imagick-3.4.4/imagick_helpers.c
	$(LIBTOOL) --mode=compile $(CC) -fopenmp -I/usr/include/ImageMagick   -I. -I/home/jeaven5/public_html/solutions/ePOS/printer/imagick-3.4.4 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/jeaven5/public_html/solutions/ePOS/printer/imagick-3.4.4/imagick_helpers.c -o imagick_helpers.lo 
imagick.lo: /home/jeaven5/public_html/solutions/ePOS/printer/imagick-3.4.4/imagick.c
	$(LIBTOOL) --mode=compile $(CC) -fopenmp -I/usr/include/ImageMagick   -I. -I/home/jeaven5/public_html/solutions/ePOS/printer/imagick-3.4.4 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/jeaven5/public_html/solutions/ePOS/printer/imagick-3.4.4/imagick.c -o imagick.lo 
imagickkernel_class.lo: /home/jeaven5/public_html/solutions/ePOS/printer/imagick-3.4.4/imagickkernel_class.c
	$(LIBTOOL) --mode=compile $(CC) -fopenmp -I/usr/include/ImageMagick   -I. -I/home/jeaven5/public_html/solutions/ePOS/printer/imagick-3.4.4 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/jeaven5/public_html/solutions/ePOS/printer/imagick-3.4.4/imagickkernel_class.c -o imagickkernel_class.lo 
shim_im6_to_im7.lo: /home/jeaven5/public_html/solutions/ePOS/printer/imagick-3.4.4/shim_im6_to_im7.c
	$(LIBTOOL) --mode=compile $(CC) -fopenmp -I/usr/include/ImageMagick   -I. -I/home/jeaven5/public_html/solutions/ePOS/printer/imagick-3.4.4 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/jeaven5/public_html/solutions/ePOS/printer/imagick-3.4.4/shim_im6_to_im7.c -o shim_im6_to_im7.lo 
$(phplibdir)/imagick.la: ./imagick.la
	$(LIBTOOL) --mode=install cp ./imagick.la $(phplibdir)

./imagick.la: $(shared_objects_imagick) $(IMAGICK_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_imagick) $(IMAGICK_SHARED_LIBADD)

